### ISSUE TITLE
Breaks FF 39

### ISSUE THREAD

**Issue by peterwthompson** [jfitzell/mozilla-keychain#80]
Enabling this addon causes the bookmarks toolbar to stop working in FF39.0 running on MacOS 10.9.5. Selective enabling of various addons has confirmed it is this one that causes a problem. In particular, subfolders of the bookmarks toolbar can no longer be opened

**Comment by jfitzell** [comment]
Does this look like the same as Issue 79?

**Comment by peterwthompson** [comment]
Yes, it is the same issue. I didn't check through the closed issues since I encountered the problem using the latest version!

**Comment by jfitzell** [comment]
I'll reopen that one since multiple people seem to be seeing it.
