### ISSUE TITLE
How to build this addon from source?

### ISSUE THREAD

**Issue by tonglil** [jfitzell/mozilla-keychain#85]
How is this addon built (I was unable to find the install instructions)?

I am only familiar with using `jpm` to package addons for development.

**Comment by jfitzell** [comment]
Just zip it and rename to .xpi

For dev it can be easier to set up a proxy file as described here: https://developer.mozilla.org/en-US/Add-ons/Setting_up_extension_development_environment#Firefox_extension_proxy_file

**Comment by tonglil** [comment]
I tried to build a copy of the addon (via zipping), but that leads to having to sign it (due to the new branded/unbranded FF versions), which led to learning how this kind of addon is built, and eventually went down a rabbithole of things.

It would be great if there are more clear instructions on how to build? I would not mind contributing (eg for the FF 49 update) if there were easy instructions in the readme :)
